include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    constant_identifier_names: false
    non_constant_identifier_names: false
    use_build_context_synchronously: false
