name: pedoman_kepengurusan_jenazah
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.1.5
  gradient_borders: ^0.2.0
  hooks_riverpod: ^1.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - contents/materi/
    - contents/muqoddimah/
    - contents/rujukan/
    - contents/author/
